name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update repos
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y build-essential libx11-dev libxft-dev libxinerama-dev libx11-xcb-dev libxcb-res0-dev
      
    - name: Compile
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: dwm-binary
        path: dwm
